ANTT_DISCIPLINES_TYPES = {
    "Topografia": ["C1", "C2"],
    "Geometria": ["A2", "F1"],
    "Terraplanagem": ["G1"],
    "Drenagem": ["H1", "H2"],
    "Sinalização": ["J1"],
    "Obras Complementares": ["J2"],
    "Pavimentação": ["I1", "I2", "C3"],
    "Estruturas": ["L1", "L2", "L3", "T1", "T2"],
    "Contenções": ["L4"],
    "Geologia": ["D1", "D2", "D3", "D4"],
    "Geotecnia": ["D5"],
    "Desapropriação": ["Q1", "Q2"],
    "Cadastro de Interferências": ["M1"],
    "Desvio de Tráfego": ["O2", "O3"],
    "Arquitetura": ["P1", "P8"],
    "Ar condicionado": ["P5"],
    "Paisagismo": ["N3", "N2"],
    "Elétrica": ["K1", "K2", "K3", "P6", "P4", "P2", "P7"],
    "Tráfego": ["E1"],
    "Planejamento": ["X2", "X4", "X5", "X6", "X9", "X7"],
    "Geral": ["Z9", "M1", "A3", "X3"],
}


ARTESP_FILE_GROUPED_TYPES = {
    "Terraplanagem": [
        "J01",
        "J02",
        "J03",
        "J04",
        "J05",
        "J09",
        "J10",
        "J11",
        "J12",
        "J13",
        "J14",
        "J15",
    ],
    "Topografia": [
        "T01",
        "T02",
        "T03",
        "T04",
        "T05",
        "T06",
        "T07",
        "T08",
        "T09",
        "T10",
        "T11",
    ],
    "Drenagem": ["H1", "H03", "H04", "H06", "H07", "H08", "H09", "H10", "H11"],
    "Geometria": ["F01", "F02", "F03", "F04", "F05", "F07", "F09", "F10", "F11"],
    "Terraplanagem": [
        "Q01",
        "Q02",
        "Q03",
        "Q04",
        "Q05",
        "Q06",
        "Q07",
        "Q09",
        "Q10",
        "Q11",
    ],
    "Pavimentação": [
        "P02",
        "P03",
        "P04",
        "P05",
        "P06",
        "P07",
        "P08",
        "P09",
        "P10",
        "P11",
        "P13",
        "P14",
    ],
    "Estruturas": ["C01", "C02", "C03", "C04", "C06", "C09", "C10", "C11"],
    "Contenções": ["C05", "C07"],
    "Sinalização": ["l01", "L02", "L03", "L04", "L05", "L06", "L09", "L11", "L12"],
    "Desvio de Tráfego": ["L07"],
    "Obras Complementares": ["L09"],
    "Cadasrto de Interferências": ["I01", "I10", "I11"],
    "Desapropriação": ["D01", "D02", "D03", "D04", "D06", "D09", "D10", "D11", "D12"],
    "Elétrica": [
        "E01",
        "E02",
        "E03",
        "E04",
        "E05",
        "E06",
        "E07",
        "E08",
        "E09",
        "E10",
        "E11",
        "E12",
    ],
    "Geologia": ["G01", "G02", "G05", "G07", "G12", "G13", "G14", "G17"],
    "Geotecnia": ["G08", "G09", "G10", "G11", "G15", "G16", "G18"],
    "Geral": [
        "S01",
        "S02",
        "S03",
        "S05",
        "S06",
        "S07",
        "S08",
        "S09",
        "S10",
        "S11",
        "S12",
        "S13",
        "S18",
        "S19",
        "Z03",
    ],
    "Arquitetura": ["k02", "K04", "K05", "K06", "K07", "K08", "K09", "K10", "K11"],
    "Planejamento": ["A07", "A09", "P01"],
    "Paisagismo": ["S04", "S09", "S14"],
}


SHEET_COLUMN_MAP = {
    # O seu SHEET_COLUMN_MAP permanece o mesmo.
    # Certifique-se de que ele inclui todos os cabeçalhos que você quer no output final.
    "PERCUSSÃO": [
        "SONDAGEM A PERCUSSÃO",
        "km",
        "PROFUNDIDADE EXECUTADA (m)",
        "NORTE",
        "LESTE",
    ],
    "TRADO": [
        "SONDAGEM A TRADO",
        "PROFUNDIDADE EXECUTADA (m)",
        "UMIDADE NATURAL",
        "DENSIDADE IN SITU",
        "LL-LP",
        "ANÁLISE GRANULOMÉTRICA COM PENEIRAMENTO E SEDIMENTAÇÃO",
        "COMPACTAÇÃO E CBR (5 PONTOS) ENERGIA PROCTOR NORMAL",
        "COMPACTAÇÃO E CBR (5 PONTOS) ENERGIA PROCTOR INTERMEDIÁRIO",
        "COMPACTAÇÃO E CBR (5 PONTOS) ENERGIA PROCTOR MODIFICADO",
        "MCT-PASTILHAS",
        "MCT-COMPLETO",
        "MÓDULO DE RESILIÊNCIA",
    ],
    "POÇO": [
        "POÇO DE INSPEÇÃO",
        "PROFUNDIDADE EXECUTADA (m)",
        "UMIDADE NATURAL",
        "DENSIDADE IN SITU",
        "LL-LP",
        "ANÁLISE GRANULOMÉTRICA COM PENEIRAMENTO E SEDIMENTAÇÃO",
        "COMPACTAÇÃO E CBR (5 PONTOS) ENERGIA PROCTOR NORMAL",
        "COMPACTAÇÃO E CBR (5 PONTOS) ENERGIA PROCTOR INTERMEDIÁRIO",
        "COMPACTAÇÃO E CBR (5 PONTOS) ENERGIA PROCTOR MODIFICADO",
        "MCT-PASTILHAS",
        "MCT-COMPLETO",
        "MÓDULO DE RESILIÊNCIA",
    ],
    "MISTA": [
        "SONDAGEM MISTA",
        "PROFUNDIDADE EXECUTADA EM SOLO (m)",
        "PROFUNDIDADE EXECUTADA EM ROCHA (m)",
    ],
    "SHELBY": [
        "AMOSTRAGEM SHELBY",
        "PROFUNDIDADE EXECUTADA (m)",
        "UMIDADE NATURAL",
        "DENSIDADE IN SITU",
        "LL-LP",
        "ANÁLISE GRANULOMÉTRICA COM PENEIRAMENTO E SEDIMENTAÇÃO",
        "COMPACTAÇÃO E CBR (5 PONTOS) ENERGIA PROCTOR NORMAL",
        "COMPACTAÇÃO E CBR (5 PONTOS) ENERGIA PROCTOR INTERMEDIÁRIO",
        "COMPACTAÇÃO E CBR (5 PONTOS) ENERGIA PROCTOR MODIFICADO",
        "MCT-PASTILHAS",
        "MCT-COMPLETO",
    ],
    "DENISON": [
        "AMOSTRAGEM DENISON",
        "PROFUNDIDADE EXECUTADA (m)",
        "UMIDADE NATURAL",
        "DENSIDADE IN SITU",
        "LL-LP",
        "ANÁLISE GRANULOMÉTRICA COM PENEIRAMENTO E SEDIMENTAÇÃO",
        "CISALHAMENTO DIRETO (AMOSTRA NATURAL)",
        "CISALHAMENTO DIRETO (AMOSTRA SATURADA)",
        "COMPACTAÇÃO E CBR (5 PONTOS) ENERGIA PROCTOR NORMAL",
        "COMPACTAÇÃO E CBR (5 PONTOS) ENERGIA PROCTOR INTERMEDIÁRIO",
        "COMPACTAÇÃO E CBR (5 PONTOS) ENERGIA PROCTOR MODIFICADO",
        "COMPRESSÃO AXIAL U",
        "TRIAXIAL UU",
        "TRIAXIAL CU",
        "TRIAXIAL CD",
        "MCT-PASTILHAS",
        "MCT-COMPLETO",
    ],
    "BLOCO": [
        "BLOCO INDEFORMADO",
        "PROFUNDIDADE EXECUTADA (m)",
        "UMIDADE NATURAL",
        "DENSIDADE IN SITU",
        "LL-LP",
        "ANÁLISE GRANULOMÉTRICA COM PENEIRAMENTO E SEDIMENTAÇÃO",
        "CISALHAMENTO DIRETO (AMOSTRA NATURAL)",
        "CISALHAMENTO DIRETO (AMOSTRA SATURADA)",
        "COMPACTAÇÃO E CBR (5 PONTOS) ENERGIA PROCTOR NORMAL",
        "COMPACTAÇÃO E CBR (5 PONTOS) ENERGIA PROCTOR INTERMEDIÁRIO",
        "COMPACTAÇÃO E CBR (5 PONTOS) ENERGIA PROCTOR MODIFICADO",
        "COMPRESSÃO AXIAL U",
        "TRIAXIAL UU",
        "TRIAXIAL CU",
        "TRIAXIAL CD",
        "MCT-PASTILHAS",
        "MCT-COMPLETO",
    ],
    "CPTU": [
        "ENSAIO DE PIEZOCONE",
        "PROFUNDIDADE PROGRAMADA MÁXIMA (m)",
        "REALIZAR ENSAIO DE DISSIPAÇÃO EM (m)",
    ],
    "VANE": [
        "ENSAIO DE PALHETA (VANE TEST)",
        "km",
        "NORTE",
        "LESTE",
        "QUANTIDADE DE ENSAIOS",
    ],
}


COLUMN_RENAME_MAP = {
    "SONDAGEM A PERCUSSÃO": "Sondagem",
    "SONDAGEM A TRADO": "Sondagem",
    "POÇO DE INSPEÇÃO": "Sondagem",
    "SONDAGEM MISTA": "Sondagem",
    "AMOSTRAGEM DENISON": "Sondagem",
    "AMOSTRAGEM SHELBY": "Sondagem",
    "BLOCO INDEFORMADO": "Sondagem",
    "ENSAIO DE PALHETA (VANE TEST)": "Sondagem",
    "ENSAIO DE PIEZOCONE": "Sondagem",
    "PROFUNDIDADE EXECUTADA (m)": "Prof. Exec. (m)",
    "PROFUNDIDADE EXECUTADA EM SOLO (m)": "Prof. Exec. Solo (m)",
    "PROFUNDIDADE EXECUTADA EM ROCHA (m)": "Prof. Exec. Rocha (m)",
    "PROFUNDIDADE PROGRAMADA MÁXIMA (m)": "Prof. Prog. Máx (m)",
    "REALIZAR ENSAIO DE DISSIPAÇÃO EM (m)": "ENSAIO DE DISSIPAÇÃO",
    "UMIDADE NATURAL": "Umidade",
    "DENSIDADE IN SITU": "Dens",
    "ANÁLISE GRANULOMÉTRICA COM PENEIRAMENTO E SEDIMENTAÇÃO": "Granulometria",
    "COMPACTAÇÃO E CBR (5 PONTOS) ENERGIA PROCTOR NORMAL": "CBR E.PN",
    "COMPACTAÇÃO E CBR (5 PONTOS) ENERGIA PROCTOR INTERMEDIÁRIO": "CBR E.PI",
    "COMPACTAÇÃO E CBR (5 PONTOS) ENERGIA PROCTOR MODIFICADO": "CBR E.PM",
    "MÓDULO DE RESILIÊNCIA": "Mód. Resiliência",
    "CISALHAMENTO DIRETO (AMOSTRA NATURAL)": "CISALHAMENTO NAT",
    "CISALHAMENTO DIRETO (AMOSTRA SATURADA)": "CISALHAMENTO SAT",
}


DISCIPLINE_SHEET_TYPES = {
    "Sondagens": ["PERCUSSÃO", "TRADO", "POÇO", "MISTA"],
    "Ensaios Especiais": ["SHELBY", "DENISON", "BLOCO", "CPTU", "VANE"],
}
